apiVersion: v1
kind: Secret
metadata:
  name: chatapp-secrets
  namespace: chat-app
type: Opaque
stringData:
  jwt: bXlTdXBlclNlY3JldDEyMw==

  CLOUDINARY_CLOUD_NAME: doraq54zs
  CLOUDINARY_API_KEY: "741165716856361"
  CLOUDINARY_API_SECRET: W6kJ__DJExSVV8w_1bOMklm2nFY